breweries =
  [{"Abandon Brewing Company", "Penn Yan", 2013},
   {"Adirondack Brewery", "Lake George", 1999},
   {"Barrage Brewing Company", "Farmingdale", 2014},
   {"Barrier Brewing Company", "Oceanside", 2010},
   {"Big Alice Brewing", "Long Island City, Queens", 2013},
   {"Blue Point Brewing Company", "Patchogue", 2014},
   {"Brewery Ommegang", "Cooperstown", 2003},
   {"Bridge and Tunnel Brewery", "Maspeth, Queens", 2012},
   {"Bronx Brewery", "The Bronx", 2014},
   {"Brooklyn Brewery", "Williamsburg, Brooklyn", 1988},
   {"Captain Lawrence Brewing Company", "Pleasantville", 2006},
   {"Chelsea Craft Brewing Company", "Chelsea, Manhattan", 1995},
   {"Coney Island Brewing Company", "Coney Island, Brooklyn", 2007},
   {"Crooked Ladder Brewing Company", "Riverhead", 2013},
   {"Dundee Brewing Company", "Rochester", 1994},
   {"Empire Brewing Company", "Syracuse", 1994},
   {"Finback Brewery", "Ridgewood, Queens", 2014},
   {"Flagship Brewing Company", "Staten Island", 2014},
   {"Flying Bison Brewing Company", "Buffalo", 2000},
   {"Genesee Brewing Company", "Rochester", 1878},
   {"Great South Bay Brewery", "Bay Shore", 2009},
   {"Greenpoint Beer & Ale Company", "Greenpoint, Brooklyn", 2014},
   {"Gun Hill Brewing Company", "The Bronx", 2014},
   {"Industrial Arts Brewing Company", "Garnerville", 2016},
   {"Keegan Ales", "Kingston", 2003},
   {"Keg & Lantern Brewing Company", "Greenpoint, Brooklyn", 2014},
   {"Kuka Andean Brewing Company", "Blauvelt", 2010},
   {"LIC Beer Project", "Long Island City, Queens", 2015},
   {"Long Ireland Beer Company", "Riverhead", 2011},
   {"Matt Brewing Company", "Utica", 1888},
   {"Other Half Brewing Company", "Carroll Gardens, Brooklyn", 2014},
   {"Rockaway Brewing Company", "Long Island City", 2011},
   {"Rohrbach Brewing Company", "Rochester", 1991},
   {"Shmaltz Brewing Company", "Clifton Park", 1996},
   {"SingleCut Beersmiths", "Astoria, Queens", 2012},
   {"Sixpoint Brewery", "Red Hook, Brooklyn", 2004},
   {"Southern Tier Brewing Company", "Lakewood", 2002},
   {"Strong Rope Brewery", "Gowanus, Brooklyn", 2015},
   {"Threes Brewing", "Gowanus, Brooklyn", 2014},
   {"Transmitter Brewing", "Queens", 2014},
   {"Upstate Brewing Company", "Elmira", 2012},
   {"War Horse Brewing Company", "Geneva", 2008}
  ]

for {brewery, _, _} <- breweries do
  IO.puts brewery
end
